# Utiliser la même image de base pour la cohérence
FROM python:3.10-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires dans le conteneur
COPY api.py .
COPY requirements.txt .
# Assurez-vous que le dossier templates et tout autre dossier nécessaire sont également copiés
COPY templates ./templates

# Mettre à jour pip et installer les dépendances à partir du fichier requirements.txt
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

# Exposer le port utilisé par Flask
EXPOSE 5000

# Définir la commande pour démarrer l'application Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
